### ISSUE TITLE
Crc32Fixup or checksums input models not working?

### ISSUE THREAD

**Issue by ghost** [aflsmart/aflsmart#11]
Hello, I don't know if your PNG Crc32Fixup works as expected with png and other file formats. I have a file format with different checksums but if afl is mutating my corpus and my Pit file defines a fix to set Crc32Fixup, is this really working at all? is peach fixing it but future mutations in afl virtual structure breaking my checksum?

https://github.com/aflsmart/aflsmart/blob/master/input_models/png.xml#L17

When I test my generated corpus there are always incorrect checksums and I don't see my coverage improve.

**Comment by thuanpv** [comment]
Hello,
The Crc32Fixup normally introduces a big overhead if we do it for every generated file so I would suggest you to disable the CRC check(s) in the code of the program/library you are testing and only fix up the interesting outputs (e.g., crash triggering files) later on. For example, to disable the CRC check in LibPNG, the following simple patch should work

`sed -i 's/return ((int)(crc != png_ptr->crc));/return (0);/g' pngrutil.c
`

Hope it helps.

Thuan

**Comment by ghost** [comment]
Thanks. I know I could remove the checksum, but my question is regarding how aflSmart works with it. Is the Crc32Fixup working? or because afl mutates the virtual structures is not working at all. 
I'm more interested in a clean PIT file with overhead than patching my sources. For example, is possible to use aflSmart with qemu mode? then I can't patch my sources but I could use my PIT file with Crc32Fixup.

Thanks

**Comment by ghost** [comment]
The author does not answer my questions, I have no interest in using aflsmart anymore.

**Comment by thuanpv** [comment]
I received another email asking the same question and I have replied to that. I think it was yours. Anyway, I can provide a patch for Crc32Fixup to work with program binaries (e.g., in Qemu mode) but the speed (execs per second) could be extremely slow, less than 1 execution per second, or even worse, because Peach must be called every time when a new test case is generated. It is not desirable so I am reluctant to commit it to the upstream. I think if you really want to disable CRC check(s) in a binary, it would not be very challenging.

**Comment by ghost** [comment]
Is possible to provide me that patch? I would like to test it with Qemu mode.Thank you

**Comment by thuanpv** [comment]
Please find attached a patch which enables constraints (e.g., CRC) repair. To test it, please use "-r N" option in which N (0->100) is the probability to invoke the repair_constraints function. For example, "-r 100" means the repair_constraints function is invoked whenever a new test case is generated and obviously this setting introduces the highest overhead.

It would be great if you could send me some feedback after trying this experimental feature.
[constraints_repair_enabled.zip](https://github.com/aflsmart/aflsmart/files/3608249/constraints_repair_enabled.zip)

**Comment by ghost** [comment]
thank you thyanpv. Do this work with QEMU? with or without the CRC checkings.

**Comment by ghost** [comment]
A 48-hour round of test with sources, I think it is right 0.78 exec/s is not worth it. I wouldn't know how to say with QEMU support. In any case an interesting experiment. Close the issue,thank you
