### ISSUE TITLE
Segmentation fault in memmove() 

### ISSUE THREAD

**Issue by chandni** [aflsmart/aflsmart#12]
I am trying to fuzz the LZ4 compression program on github at https://github.com/lz4/lz4, particularly this release: https://github.com/lz4/lz4/releases/tag/r121. I am trying to use AFLSMART to fuzz this but currently I get a segmentation fault immediately after starting the fuzzer. The program works with afl. 
Here is the command line I am using to run aflsmart with lz4c32: 

 $AFLSMART/afl-fuzz -h  -i `realpath $AFLSMART/testcases/aflsmart/lz4` -o output -w peach -g `realpath $AFLSMART/input_models/lz4_1.xml` $WORKDIR/lz4-r131/programs/lz4c32 @@

I get this segmentation fault immediately (running inside gdb):
Program received signal SIGSEGV, Segmentation fault.
__memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:371
371     ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No such file or directory.

********backtrace info:************

#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:371
#1  0x000055555556befe in memmove (__len=<optimized out>, __src=<optimized out>, __dest=<optimized out>) at /usr/include/x86_64-linux-gnu/bits/string_fortified.h:40
#2  higher_order_fuzzing (current_queue_entry=0x55555588b3e8, temp_len=0x7fffffffdbb0, out_buf=0x7fffffffdba0, alloc_size=<optimized out>) at afl-fuzz.c:5448
#3  0x000055555556e688 in fuzz_one (argv=<optimized out>) at afl-fuzz.c:7336
#4  0x0000555555558fd3 in main (argc=<optimized out>, argv=<optimized out>) at afl-fuzz.c:9144
************************************************************************
The exact line of failure is: https://github.com/aflsmart/aflsmart/blob/master/afl-fuzz.c#L5448
************************************************************************
Printing out the individual values shows:
 "(*temp_len) - del_from - del_len + 1  = 4294967289" (REALLY BIG VALUE!)
 (*temp_len) = 22243
 del_from = 22247. 
So del_from > *(temp_len). 

After tracing where del_from is getting set, I see it is getting set at line no.5275  inside function get_chunk_to_delete() here: https://github.com/aflsmart/aflsmart/blob/master/afl-fuzz.c#L5275:  
********************
*del_from = start_byte
********************
 This is output of list in gdb: 

**********************
if (start_byte >= 0 &&
--
  | chunk_to_delete->end_byte >= start_byte) {
  | /* Note that the length to be deleted here is 1 more than
  | end_byte - start_byte, since the end_byte is exactly the
  | position of the last byte, not one more than the last
  | byte. */
  | *del_from = start_byte;
  | *del_len = chunk_to_delete->end_byte - start_byte + 1;
  | break;
  | }

**************************

**Comment by thuanpv** [comment]
As discussed over email, the issue is in the input model. I close this issue but please feel free to open it again.
