### ISSUE TITLE
'flag' type in input model causes overread

### ISSUE THREAD

**Issue by jaiverma** [aflsmart/aflsmart#19]
The following peach pit reproduces this issue:
```xml
<DataModel name='Header'>
    <String name="magic" value="6230306d" valueType="hex" token="true" mutable="false" />
    <Flags name="fl4g" size="8">
        <Flag name="f_a" size="1" position="0" />
        <Flag name="f_b" size="1" position="1" />
        <Flag name="f_c" size="1" position="2" />
    </Flags>
    <Number name="num" size="32" />
</DataModel>
```
The problem is in the patch where we are adding the `LengthBytes` to find out how many bytes an element consumes.
```csharp
outputFile.WriteLine ("{0},{1},{2},{3}", pos, pos + node.Value.LengthBytes - 1, strName, "Enabled");
```

Here we have 3 `<Flag>` elements inside a `<Flags>` element. The `lengthType` of `Flag` is actually `LengthType.Bits`.

For a file of 9 bytes, running Peach gives us the following `.chunks` file:
```sh
$ peach -1 test.xml -inputFilePath=test2.dat -outputFilePath=new.dat
```

Output:
```
0,8,mydata,Enabled
0,8,mydata~header,Enabled
0,8,mydata~header~header,Enabled
0,3,mydata~header~header~magic,Disabled
4,4,mydata~header~header~fl4g,Enabled
4,4,mydata~header~header~fl4g~f_a,Enabled
5,5,mydata~header~header~fl4g~f_b,Enabled
6,6,mydata~header~header~fl4g~f_c,Enabled
7,10,mydata~header~header~num,Enabled
```

The actual size of the file is 9 bytes.
```sh
$ ls -l test2.dat
-rw-r--r-- 1 root root 9 Jan 20 14:14 test2.dat
$ hd test2.dat
00000000  62 30 30 6d 05 0f 00 00  00                       |b00m.....|
00000009
```

Is there a workaround to this? I guess `aflsmart` doesn't define chunks at such a granular bit level and it is save to remove the individual `<Flag>` definitions and replace it with just one `<Flags>` element or a `<Number>` element.

**Comment by thuanpv** [comment]
Hi jaiverma,

Thank you for reporting this issue with a concrete example. As you already pointed out, AFLSmart assumes that the input models are defined at byte-level granularity. It has been (indirectly) stated in sections 4.2 and 4.3 of our TSE paper: https://thuanpv.github.io/publications/TSE19_aflsmart.pdf. AFLSmart's chunk-level mutators are supposed to work at multiple-byte chunks and leave more fine-grained mutation jobs for original AFL's mutators. 

In your example, I would suggest that you replace multiple `<Flag>` elements by the `<Flags>` or `<Number>` elements.

I hope it helps.
Thuan

**Comment by jaiverma** [comment]
Thank you for the clarification Thuan!
Closing the issue.
