### ISSUE TITLE
Unmodifiable chunks

### ISSUE THREAD

**Issue by mgayanov** [aflsmart/aflsmart#20]
Hello! Thank you for your work!

I need AFLSMART not to change chunks that have the `modifiable="false"` attribute in peach pit file.

But I found that the fuzzer ignores this attribute.

The structure of the chunks has a field named `char modifiable`, which becomes false if the `modifiable="false"` attribute for this chunk is set.

```c
struct chunk {
  unsigned long id; /* The id of the chunk, which either equals its pointer value or, when
                                 loaded from chunks file, equals to the hashcode of its chunk
                                 identifer string casted to unsigned long. */
  int type;                /* The hashcode of the chunk type. */
  int start_byte;          /* The start byte, negative if unknown. */
  int end_byte;            /* The last byte, negative if unknown. */
  char modifiable;         /* The modifiable flag. */
  struct chunk *next;      /* The next sibling child. */
  struct chunk *children;  /* The children chunks linked list. */
};
```

But I did not find where this field would be used.

For example, the `get_chunk_to_delete` function does not look at variable `chunk_to_delete->modifiable` before return this chunk for deletion.
https://github.com/aflsmart/aflsmart/blob/master/afl-fuzz.c#L5269

If I’m wrong, could you write how to make the chunks not modified?

**Comment by thuanpv** [comment]
Thank you for bringing it up and for sending a pull request to check the modifiable flag before deleting a chunk. I have merged it to the master.
