### ISSUE TITLE
Can it work like winafl?

### ISSUE THREAD

**Issue by ghost** [aflsmart/aflsmart#27]
Will this project work on windows platform in future?

**Comment by thuanpv** [comment]
Hi @Bit-flipper,

AFLSmart is built on top of AFL and the same idea is platform independent. To support Windows, the most obvious option is to port AFLSmart to WinAFL. And the main required changes are 1) porting AFLSmart-specific code to WinAFL and 2) using Peach on Windows. Both tasks are quite straightforward but we haven't had time to work on them yet. Contributions (e.g., PRs) are welcome!

Cheers,

Thuan

**Comment by ghost** [comment]
Thanks for your precious time!!!
