### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [aflsmart/aflsmart#4]
[An extra null pointer check is not needed](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") in [the function “get_chunks”](https://github.com/aflsmart/aflsmart/blob/6c69a23f37341d0e865e870a7afb1cdeef6f3ef3/smart-chunks.c#L286 "Update candidate").

**Comment by mboehme** [comment]
Hi Markus: We are currently focussing our resources on another project. 
In the meantime, you are welcome to send us a pull request fixing the three reported issues :)

**Comment by thuanpv** [comment]
Close this as no more information is provided.
