### ISSUE TITLE
Some errors when compile the code

### ISSUE THREAD

**Issue by fanjingwei** [aflsmart/aflsmart#5]
when use 'make clean all' to compile the code, the follow error appears:
‘for’ loop initial declarations are only allowed in C99 mode

but when use 'CFLAGS='-std=c99' make clean all' to compile the code another error appears:
types.h:81:3: error: ‘asm’ undeclared (first use in this function)
   asm volatile("" ::: "memory")
   ^

At last i modify the code form 'for (u8 i = 0; i < 3; ++i)' to 'u8 i=0; for (i=0; i<3; ++i)' to fix the compile error.

**Comment by mboehme** [comment]
Thanks for reporting! Fixed.

**Comment by selfbypass** [comment]
Now, I have met the same error!
