### ISSUE TITLE
about AFL's qemu mode

### ISSUE THREAD

**Issue by E4ck** [aflsmart/aflsmart#6]
Hi,
I want to know if the generated pit is equally applicable to the AFL qmeu mode.

**Comment by mboehme** [comment]
I see no reason why it shouldn't work. Only the fuzzer (afl-fuzz.c) was modified. The program instrumentation remains as is: https://github.com/aflsmart/aflsmart/compare/2fb5a34..master

**Comment by E4ck** [comment]
OK, thanks
