### ISSUE TITLE
Readme indicates dictionary + model file

### ISSUE THREAD

**Issue by TomAnthony** [aflsmart/aflsmart#7]
The AFLSmart readme indicates you can use the `-x` and `-w` / `-g` together:

```
afl-fuzz -h -i in -o out -w peach -g <input model file> -x <dictionary file> <executable binary and its arguments> @@
```

However, as soon as the `-g` parameter is passed, it appears to only use `havoc` mode (all the other modes show `n/a`), which implies the dictionary is not being used.

Does anyone know what is going on here?

**Comment by thuanpv** [comment]
Hi,

> However, as soon as the -g parameter is passed, it appears to only use havoc mode (all the other modes show n/a), which implies the dictionary is not being used.

The havoc stage does not *automatically infer* the dictionary (i.e., extras) like what AFL does in its deterministic phase but it does use the provided/inferred dictionary/extras. You can take a look at cases 15 & 16 in afl-fuzz.c (lines 6375-6450) of AFL v2.52b (https://github.com/mirrorer/afl/blob/master/afl-fuzz.c) or cases 15 & 16 & 17 in AFLSmart.

Hope it answers your question.

Thuan

**Comment by TomAnthony** [comment]
Hey Thuan,

Thanks a lot for the quick reply.

I was surprised it was only running Havoc mode, but seeing that it uses the dictionary differently makes sense. :)

-Tom
