### ISSUE TITLE
parallel fuzzing

### ISSUE THREAD

**Issue by ghost** [aflsmart/aflsmart#8]
How can I fuzz in parallel master-slave? It seems not supported. If I need different docker or vms, there is no sync between them, right?

**Comment by thuanpv** [comment]
AFLSmart does work in parallel mode. I would suggest you run one instance of normal AFL in master mode (-M) and several instances of AFLSmart in slave mode (-S). As reported in our Arxiv preprint, I ran AFLSmart in parallel mode to find several vulnerabilities in FFmpeg.

**Comment by alexandermitop** [comment]
Could you tell me why this version of peach does not accept Calc? http://community.peachfuzzer.com/v3/lengthCalc.html
I am creating a peach for a test project but it is impossible for me to generate a Blob or string like that.

<String value="MAGIC" lengthType="calc" lengthCalc="len(self.name)"/>

Error, parsing lengthType on 'MAGIC', unknown value: 'calc'.
