### ISSUE TITLE
gcc supported version? (only 4.4)

### ISSUE THREAD

**Issue by thinkycx** [aflsmart/aflsmart#9]
```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt install gcc-4.4
sudo apt install g++-4.4
```
gcc-4.4 is not exists on ubuntu18.04 (16.04 is ok) : https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test?field.series_filter=xenial

I wonder that only gcc-4.4 is supported?
>as Pin component in Peach has a compilation issue with newer version of gcc like gcc-5.4)

Does any other gcc version is supported? as I want to build it in other platforms such as aarch64.
such as gcc 7 gcc 8?

**Comment by thuanpv** [comment]
Hello,

I think all versions between 4.1 and 4.4 would work because I did not need Gcc-4.4 when I first developed AFLSmart on Ubuntu 14.04 which has gcc-4.1 as the default GCC version, if I remember correctly.

Hope it helps.

Thuan

**Comment by thinkycx** [comment]
> Hello,
> 
> I think all versions between 4.1 and 4.4 would work because I did not need Gcc-4.4 when I first developed AFLSmart on Ubuntu 14.04 which has gcc-4.1 as the default GCC version, if I remember correctly.
> 
> Hope it helps.
> 
> Thuan

Thank you.
